remote_theme: pages-themes/cayman@v0.2.0
markdown: GFM
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
links:
  # paper: 
  code: "https://github.com/maks00170/PM_AUDIO"